name: Tests 

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java 23
      - name: Setup JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: gradle

      # Grant permissions to gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build and run tests
      - name: Build and test with Gradle
        run: ./gradlew test

      # Build and check formatting
      - name: Build and check formatting
        run: ./gradlew spotlessCheck build
